package com.xafero.nice.swing;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JPanel;

public class GradientPanel extends JPanel {
    
    private Color firstColor = Color.black;
    private Color secondColor = Color.white;
    private GradientMode mode = GradientMode.Vertical;

    /**
     * Creates new form GradientPanel
     */
    public GradientPanel() {
        initComponents();
    }
    
    public Color getFirstColor() {
        return firstColor;
    }
    
    public void setFirstColor(Color firstColor) {
        this.firstColor = firstColor;
    }
    
    public Color getSecondColor() {
        return secondColor;
    }
    
    public void setSecondColor(Color secondColor) {
        this.secondColor = secondColor;
    }
    
    public GradientMode getMode() {
        return mode;
    }
    
    public void setMode(GradientMode mode) {
        this.mode = mode;
    }
    
    @Override
    protected void paintComponent(Graphics grphcs) {
        super.paintComponent(grphcs);
        Graphics2D g = (Graphics2D) grphcs;
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        GradientPaint gp;
        switch (mode) {
            case Horizontal:
                gp = new GradientPaint(0, 0, firstColor, getWidth(), 0, secondColor);
                break;
            case Vertical:
            default:
                gp = new GradientPaint(0, 0, firstColor, 0, getHeight(), secondColor);
                break;
        }
        g.setPaint(gp);
        g.fillRect(0, 0, getWidth(), getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
